# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/7597ECC22B316B49/programs/linux/calibre/src/calibre/gui2/viewer/qdialog/qdialogConfig.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(I("config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border-radius: 5px;\n"
"     color: black;\n"
"     font-weight: bold;\n"
" }\n"
"\n"
" QToolBox::tab:selected {\n"
"     font-style: italic;\n"
" }\n"
"\n"
"QToolBox::tab:hover {\n"
"   color: red;\n"
"   font-style: italic;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 524, 370))
        self.page.setObjectName("page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mono_family = QtWidgets.QFontComboBox(self.groupBox_6)
        self.mono_family.setObjectName("mono_family")
        self.gridLayout_9.addWidget(self.mono_family, 2, 1, 1, 1)
        self.serif_family = QtWidgets.QFontComboBox(self.groupBox_6)
        self.serif_family.setObjectName("serif_family")
        self.gridLayout_9.addWidget(self.serif_family, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 3, 0, 1, 1)
        self.sans_family = QtWidgets.QFontComboBox(self.groupBox_6)
        self.sans_family.setObjectName("sans_family")
        self.gridLayout_9.addWidget(self.sans_family, 1, 1, 1, 1)
        self.standard_font = QtWidgets.QComboBox(self.groupBox_6)
        self.standard_font.setObjectName("standard_font")
        self.standard_font.addItem("")
        self.standard_font.addItem("")
        self.standard_font.addItem("")
        self.gridLayout_9.addWidget(self.standard_font, 3, 1, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 4, 0, 1, 1)
        self.font_magnification_step = QtWidgets.QSpinBox(self.groupBox_7)
        self.font_magnification_step.setObjectName("font_magnification_step")
        self.gridLayout_10.addWidget(self.font_magnification_step, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 3, 0, 1, 1)
        self.mono_font_size = QtWidgets.QSpinBox(self.groupBox_7)
        self.mono_font_size.setMinimum(8)
        self.mono_font_size.setMaximum(100)
        self.mono_font_size.setObjectName("mono_font_size")
        self.gridLayout_10.addWidget(self.mono_font_size, 1, 1, 1, 1)
        self.minimum_font_size = QtWidgets.QSpinBox(self.groupBox_7)
        self.minimum_font_size.setMinimum(8)
        self.minimum_font_size.setObjectName("minimum_font_size")
        self.gridLayout_10.addWidget(self.minimum_font_size, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.default_font_size = QtWidgets.QSpinBox(self.groupBox_7)
        self.default_font_size.setMinimum(8)
        self.default_font_size.setMaximum(100)
        self.default_font_size.setObjectName("default_font_size")
        self.gridLayout_10.addWidget(self.default_font_size, 0, 1, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupBox_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.toolBox.addItem(self.page, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 524, 368))
        self.page_5.setObjectName("page_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.page_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 0, 1, 1)
        self.cols_per_screen_portrait = QtWidgets.QSpinBox(self.groupBox_2)
        self.cols_per_screen_portrait.setMinimum(1)
        self.cols_per_screen_portrait.setMaximum(5)
        self.cols_per_screen_portrait.setObjectName("cols_per_screen_portrait")
        self.gridLayout_2.addWidget(self.cols_per_screen_portrait, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 0, 1, 1)
        self.cols_per_screen_landscape = QtWidgets.QSpinBox(self.groupBox_2)
        self.cols_per_screen_landscape.setMinimum(1)
        self.cols_per_screen_landscape.setMaximum(5)
        self.cols_per_screen_landscape.setObjectName("cols_per_screen_landscape")
        self.gridLayout_2.addWidget(self.cols_per_screen_landscape, 1, 1, 1, 1)
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bottom_margin = QtWidgets.QSpinBox(self.groupBox_3)
        self.bottom_margin.setMinimum(10)
        self.bottom_margin.setMaximum(1000)
        self.bottom_margin.setObjectName("bottom_margin")
        self.gridLayout_3.addWidget(self.bottom_margin, 3, 1, 1, 1)
        self.top_margin = QtWidgets.QSpinBox(self.groupBox_3)
        self.top_margin.setMinimum(10)
        self.top_margin.setMaximum(1000)
        self.top_margin.setObjectName("top_margin")
        self.gridLayout_3.addWidget(self.top_margin, 1, 1, 1, 1)
        self.use_book_margins = QtWidgets.QCheckBox(self.groupBox_3)
        self.use_book_margins.setChecked(True)
        self.use_book_margins.setObjectName("use_book_margins")
        self.gridLayout_3.addWidget(self.use_book_margins, 0, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.side_margin = QtWidgets.QSpinBox(self.groupBox_3)
        self.side_margin.setMinimum(10)
        self.side_margin.setMaximum(1000)
        self.side_margin.setObjectName("side_margin")
        self.gridLayout_3.addWidget(self.side_margin, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.hyphenate = QtWidgets.QCheckBox(self.page_5)
        self.hyphenate.setObjectName("hyphenate")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.hyphenate)
        self.hyphenate_default_lang = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hyphenate_default_lang.sizePolicy().hasHeightForWidth())
        self.hyphenate_default_lang.setSizePolicy(sizePolicy)
        self.hyphenate_default_lang.setObjectName("hyphenate_default_lang")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hyphenate_default_lang)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(9, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.toolBox.addItem(self.page_5, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 537, 233))
        self.page_2.setObjectName("page_2")
        self.formLayout = QtWidgets.QFormLayout(self.page_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.max_fs_width = QtWidgets.QSpinBox(self.groupBox_5)
        self.max_fs_width.setMinimum(100)
        self.max_fs_width.setMaximum(10000)
        self.max_fs_width.setObjectName("max_fs_width")
        self.gridLayout_8.addWidget(self.max_fs_width, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 1, 0, 1, 1)
        self.max_fs_height = QtWidgets.QSpinBox(self.groupBox_5)
        self.max_fs_height.setMinimum(100)
        self.max_fs_height.setMaximum(10000)
        self.max_fs_height.setSingleStep(25)
        self.max_fs_height.setObjectName("max_fs_height")
        self.gridLayout_8.addWidget(self.max_fs_height, 1, 1, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_5)
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.fullscreen_pos = QtWidgets.QCheckBox(self.groupBox_10)
        self.fullscreen_pos.setObjectName("fullscreen_pos")
        self.gridLayout_11.addWidget(self.fullscreen_pos, 0, 0, 1, 1)
        self.fullscreen_scrollbar = QtWidgets.QCheckBox(self.groupBox_10)
        self.fullscreen_scrollbar.setObjectName("fullscreen_scrollbar")
        self.gridLayout_11.addWidget(self.fullscreen_scrollbar, 0, 1, 1, 1)
        self.show_fullscreen_help = QtWidgets.QCheckBox(self.groupBox_10)
        self.show_fullscreen_help.setObjectName("show_fullscreen_help")
        self.gridLayout_11.addWidget(self.show_fullscreen_help, 0, 2, 1, 1)
        self.fullscreen_clock = QtWidgets.QCheckBox(self.groupBox_10)
        self.fullscreen_clock.setObjectName("fullscreen_clock")
        self.gridLayout_11.addWidget(self.fullscreen_clock, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 4, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox_10)
        self.start_in_fullscreen = QtWidgets.QCheckBox(self.page_2)
        self.start_in_fullscreen.setObjectName("start_in_fullscreen")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.start_in_fullscreen)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.toolBox.addItem(self.page_2, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 537, 233))
        self.page_6.setObjectName("page_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.page_6)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_color_sample = QtWidgets.QLabel(self.page_6)
        self.text_color_sample.setStyleSheet("QLabel {\n"
"    border-style: solid !important;\n"
"    border-width: 1px !important;\n"
"}")
        self.text_color_sample.setText("")
        self.text_color_sample.setObjectName("text_color_sample")
        self.horizontalLayout_2.addWidget(self.text_color_sample)
        self.change_text_color_button = QtWidgets.QToolButton(self.page_6)
        self.change_text_color_button.setObjectName("change_text_color_button")
        self.horizontalLayout_2.addWidget(self.change_text_color_button)
        self.reset_text_color_button = QtWidgets.QToolButton(self.page_6)
        self.reset_text_color_button.setObjectName("reset_text_color_button")
        self.horizontalLayout_2.addWidget(self.reset_text_color_button)
        self.formLayout_6.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.background_color_sample = QtWidgets.QLabel(self.page_6)
        self.background_color_sample.setStyleSheet("QLabel {\n"
"    border-style: solid !important;\n"
"    border-width: 1px !important;\n"
"}")
        self.background_color_sample.setText("")
        self.background_color_sample.setObjectName("background_color_sample")
        self.horizontalLayout.addWidget(self.background_color_sample)
        self.change_background_color_button = QtWidgets.QToolButton(self.page_6)
        self.change_background_color_button.setObjectName("change_background_color_button")
        self.horizontalLayout.addWidget(self.change_background_color_button)
        self.reset_background_color_button = QtWidgets.QToolButton(self.page_6)
        self.reset_background_color_button.setObjectName("reset_background_color_button")
        self.horizontalLayout.addWidget(self.reset_background_color_button)
        self.formLayout_6.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.save_theme_button = QtWidgets.QToolButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(I("save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_theme_button.setIcon(icon1)
        self.save_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.save_theme_button.setObjectName("save_theme_button")
        self.horizontalLayout_4.addWidget(self.save_theme_button)
        self.load_theme_button = QtWidgets.QToolButton(self.groupBox_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(I("document_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_theme_button.setIcon(icon2)
        self.load_theme_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.load_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.load_theme_button.setObjectName("load_theme_button")
        self.horizontalLayout_4.addWidget(self.load_theme_button)
        self.delete_theme_button = QtWidgets.QToolButton(self.groupBox_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(I("trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_theme_button.setIcon(icon3)
        self.delete_theme_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.delete_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_theme_button.setObjectName("delete_theme_button")
        self.horizontalLayout_4.addWidget(self.delete_theme_button)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.theming_message = QtWidgets.QLabel(self.groupBox_4)
        self.theming_message.setText("")
        self.theming_message.setObjectName("theming_message")
        self.gridLayout_7.addWidget(self.theming_message, 0, 0, 1, 1)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_6.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.toolBox.addItem(self.page_6, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, -20, 524, 267))
        self.page_3.setObjectName("page_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.page_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.page_flip_duration = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.page_flip_duration.setDecimals(1)
        self.page_flip_duration.setMinimum(0.1)
        self.page_flip_duration.setMaximum(3.0)
        self.page_flip_duration.setSingleStep(0.1)
        self.page_flip_duration.setProperty("value", 0.5)
        self.page_flip_duration.setObjectName("page_flip_duration")
        self.gridLayout_5.addWidget(self.page_flip_duration, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tap_flips_pages = QtWidgets.QCheckBox(self.groupBox_11)
        self.tap_flips_pages.setObjectName("tap_flips_pages")
        self.horizontalLayout_8.addWidget(self.tap_flips_pages)
        self.wheel_flips_pages = QtWidgets.QCheckBox(self.groupBox_11)
        self.wheel_flips_pages.setObjectName("wheel_flips_pages")
        self.horizontalLayout_8.addWidget(self.wheel_flips_pages)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox_11)
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 0, 0, 1, 1)
        self.wheel_scroll_fraction = QtWidgets.QSpinBox(self.groupBox)
        self.wheel_scroll_fraction.setMinimum(1)
        self.wheel_scroll_fraction.setMaximum(2000)
        self.wheel_scroll_fraction.setSingleStep(5)
        self.wheel_scroll_fraction.setObjectName("wheel_scroll_fraction")
        self.gridLayout_6.addWidget(self.wheel_scroll_fraction, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 1, 0, 1, 1)
        self.line_scroll_fraction = QtWidgets.QSpinBox(self.groupBox)
        self.line_scroll_fraction.setMinimum(1)
        self.line_scroll_fraction.setMaximum(2000)
        self.line_scroll_fraction.setSingleStep(5)
        self.line_scroll_fraction.setObjectName("line_scroll_fraction")
        self.gridLayout_6.addWidget(self.line_scroll_fraction, 1, 1, 1, 1)
        self.line_scrolling_stops_on_pagebreaks = QtWidgets.QCheckBox(self.groupBox)
        self.line_scrolling_stops_on_pagebreaks.setObjectName("line_scrolling_stops_on_pagebreaks")
        self.gridLayout_6.addWidget(self.line_scrolling_stops_on_pagebreaks, 2, 0, 1, 2)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem6)
        self.toolBox.addItem(self.page_3, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 537, 233))
        self.page_7.setObjectName("page_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dictionary_list = QtWidgets.QListWidget(self.page_7)
        self.dictionary_list.setObjectName("dictionary_list")
        self.gridLayout_4.addWidget(self.dictionary_list, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_dictionary_website_button = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.add_dictionary_website_button.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(I("plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_dictionary_website_button.setIcon(icon4)
        self.add_dictionary_website_button.setObjectName("add_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.add_dictionary_website_button)
        self.remove_dictionary_website_button = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.remove_dictionary_website_button.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(I("minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_dictionary_website_button.setIcon(icon5)
        self.remove_dictionary_website_button.setObjectName("remove_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.remove_dictionary_website_button)
        self.change_dictionary_website_button = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_dictionary_website_button.sizePolicy().hasHeightForWidth())
        self.change_dictionary_website_button.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(I("edit_input.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_dictionary_website_button.setIcon(icon6)
        self.change_dictionary_website_button.setObjectName("change_dictionary_website_button")
        self.horizontalLayout_3.addWidget(self.change_dictionary_website_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 537, 233))
        self.page_8.setObjectName("page_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_8 = QtWidgets.QLabel(self.page_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.synopsis_extension = QtWidgets.QLineEdit(self.page_8)
        self.synopsis_extension.setObjectName("synopsis_extension")
        self.gridLayout_12.addWidget(self.synopsis_extension, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem8, 2, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_8)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.synopsis_position = QtWidgets.QCheckBox(self.groupBox_12)
        self.synopsis_position.setObjectName("synopsis_position")
        self.horizontalLayout_7.addWidget(self.synopsis_position)
        self.synopsis_size = QtWidgets.QCheckBox(self.groupBox_12)
        self.synopsis_size.setObjectName("synopsis_size")
        self.horizontalLayout_7.addWidget(self.synopsis_size)
        self.gridLayout_12.addWidget(self.groupBox_12, 1, 0, 1, 4)
        self.toolBox.addItem(self.page_8, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, -29, 524, 262))
        self.page_4.setObjectName("page_4")
        self.gridLayout = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.remember_window_size = QtWidgets.QCheckBox(self.groupBox_8)
        self.remember_window_size.setObjectName("remember_window_size")
        self.horizontalLayout_5.addWidget(self.remember_window_size)
        self.remember_current_page = QtWidgets.QCheckBox(self.groupBox_8)
        self.remember_current_page.setObjectName("remember_current_page")
        self.horizontalLayout_5.addWidget(self.remember_current_page)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.remember_current_page.raise_()
        self.remember_window_size.raise_()
        self.gridLayout.addWidget(self.groupBox_8, 5, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fit_images = QtWidgets.QCheckBox(self.groupBox_9)
        self.fit_images.setObjectName("fit_images")
        self.horizontalLayout_6.addWidget(self.fit_images)
        self.singleinstance = QtWidgets.QCheckBox(self.groupBox_9)
        self.singleinstance.setObjectName("singleinstance")
        self.horizontalLayout_6.addWidget(self.singleinstance)
        self.show_controls = QtWidgets.QCheckBox(self.groupBox_9)
        self.show_controls.setObjectName("show_controls")
        self.horizontalLayout_6.addWidget(self.show_controls)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.show_controls.raise_()
        self.singleinstance.raise_()
        self.fit_images.raise_()
        self.gridLayout.addWidget(self.groupBox_9, 4, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.copy_bookmarks_to_file = QtWidgets.QCheckBox(self.page_4)
        self.copy_bookmarks_to_file.setObjectName("copy_bookmarks_to_file")
        self.gridLayout.addWidget(self.copy_bookmarks_to_file, 6, 0, 1, 2)
        self.search_online_url = QtWidgets.QLineEdit(self.page_4)
        self.search_online_url.setObjectName("search_online_url")
        self.gridLayout.addWidget(self.search_online_url, 3, 1, 1, 1)
        self.clear_search_history_button = QtWidgets.QPushButton(self.page_4)
        self.clear_search_history_button.setObjectName("clear_search_history_button")
        self.gridLayout.addWidget(self.clear_search_history_button, 7, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 8, 0, 1, 2)
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.user_css = QtWidgets.QPlainTextEdit(self.tab_3)
        self.user_css.setObjectName("user_css")
        self.verticalLayout_3.addWidget(self.user_css)
        self.tabs.addTab(self.tab_3, "")
        self.verticalLayout_5.addWidget(self.tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)
        self.label_3.setBuddy(self.mono_family)
        self.label_2.setBuddy(self.sans_family)
        self.label.setBuddy(self.serif_family)
        self.label_6.setBuddy(self.standard_font)
        self.label_12.setBuddy(self.font_magnification_step)
        self.label_5.setBuddy(self.mono_font_size)
        self.label_22.setBuddy(self.minimum_font_size)
        self.label_4.setBuddy(self.default_font_size)
        self.label_27.setBuddy(self.cols_per_screen_portrait)
        self.label_28.setBuddy(self.cols_per_screen_landscape)
        self.label_19.setBuddy(self.side_margin)
        self.label_17.setBuddy(self.bottom_margin)
        self.label_18.setBuddy(self.top_margin)
        self.label_7.setBuddy(self.max_fs_width)
        self.label_11.setBuddy(self.page_flip_duration)
        self.label_29.setBuddy(self.wheel_scroll_fraction)
        self.label_30.setBuddy(self.line_scroll_fraction)
        self.label_26.setBuddy(self.search_online_url)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(6)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.use_book_margins.toggled['bool'].connect(self.side_margin.setEnabled)
        self.use_book_margins.toggled['bool'].connect(self.bottom_margin.setEnabled)
        self.use_book_margins.toggled['bool'].connect(self.top_margin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):

        Dialog.setWindowTitle(_("Configure Ebook viewer"))
        self.groupBox_6.setTitle(_("Family"))
        self.label_3.setText(_("&Monospace"))
        self.label_2.setText(_("&Sans"))
        self.label.setText(_("Se&rif"))
        self.label_6.setText(_("S&tandard"))
        self.standard_font.setItemText(0, _("Serif"))
        self.standard_font.setItemText(1, _("Sans-serif"))
        self.standard_font.setItemText(2, _("Monospace"))
        self.groupBox_7.setTitle(_("Size"))
        self.label_12.setText(_("Magnification step"))
        self.font_magnification_step.setToolTip(_("The amount by which the font size is increased/decreased\n"
" when you click the font size larger/smaller buttons"))
        self.font_magnification_step.setSuffix(_("%"))
        self.label_5.setText(_("Monospace "))
        self.label_22.setText(_("Minimum"))
        self.mono_font_size.setSuffix(_(" px"))
        self.minimum_font_size.setToolTip(_("The minimum font size in pixels"))
        self.minimum_font_size.setSuffix(_(" px"))
        self.label_4.setText(_("&Default"))
        self.default_font_size.setSuffix(_(" px"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _("&Font"))
        self.groupBox_2.setToolTip(_("The number of pages of text to show on screen "))
        self.groupBox_2.setTitle(_("Pages"))
        self.label_27.setText(_("Portrait"))
        self.cols_per_screen_portrait.setToolTip(_("Controls the number of pages on the screen when the viewer window\'s width is less than its height"))
        self.label_28.setText(_("Landscape"))
        self.cols_per_screen_landscape.setToolTip(_("Controls the number of pages on the screen when the viewer window\'s height is less than its width"))
        self.groupBox_3.setTitle(_("Margin"))
        self.bottom_margin.setSuffix(_(" px"))
        self.top_margin.setSuffix(_(" px"))
        self.use_book_margins.setText(_("&Override the page margin settings specified in the book"))
        self.label_19.setText(_("Side"))
        self.side_margin.setSuffix(_(" px"))
        self.label_17.setText(_("Bottom"))
        self.label_18.setText(_("Top"))
        self.hyphenate.setToolTip(_("break line in the middle of large words"))
        self.hyphenate.setText(_("H&yphenation language"))
        self.hyphenate_default_lang.setToolTip(_("The default language to use for hyphenation rules. If the book does not specify a language, this will be used."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _("Text &layout"))
        self.groupBox_5.setTitle(_("Text maximum size"))
        self.label_7.setText(_("Width"))
        self.max_fs_width.setToolTip(_("Set the maximum width that the book\'s text and pictures will take when in fullscreen mode. This allows you to read the book text without it becoming too wide."))
        self.max_fs_width.setSuffix(_(" px"))
        self.label_24.setToolTip(_("Only available on paged mode"))
        self.label_24.setText(_("Height"))
        self.max_fs_height.setSpecialValueText(_("Disabled"))
        self.max_fs_height.setSuffix(_(" px"))
        self.groupBox_10.setTitle(_("Elements"))
        self.fullscreen_pos.setText(_("&Position "))
        self.fullscreen_scrollbar.setText(_("&Scrollbar"))
        self.show_fullscreen_help.setText(_("&Help"))
        self.fullscreen_clock.setText(_("&Clock "))
        self.start_in_fullscreen.setText(_("&Start full screen "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _("F&ull screen"))
        self.label_16.setText(_("Text "))
        self.change_text_color_button.setText(_("Edit"))
        self.reset_text_color_button.setText(_("Reset"))
        self.label_14.setText(_("Background "))
        self.change_background_color_button.setText(_("Edit"))
        self.reset_background_color_button.setText(_("Reset"))
        self.groupBox_4.setTitle(_("Theme"))
        self.save_theme_button.setToolTip(_("Save current theme"))
        self.save_theme_button.setText(_("&Save"))
        self.load_theme_button.setToolTip(_("Load theme"))
        self.load_theme_button.setText(_("&Load"))
        self.delete_theme_button.setToolTip(_("Delete theme"))
        self.delete_theme_button.setText(_("&Delete"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _("Color"))
        self.groupBox_11.setToolTip(_("tapping on page flips pages"))
        self.groupBox_11.setTitle(_("Flip"))
        self.label_11.setText(_("&Duration"))
        self.page_flip_duration.setSpecialValueText(_("disabled"))
        self.page_flip_duration.setSuffix(_(" secs"))
        self.tap_flips_pages.setText(_("&Tapping "))
        self.wheel_flips_pages.setToolTip(_("mouse wheel flips pages"))
        self.wheel_flips_pages.setText(_("Mouse &wheel "))
        self.groupBox.setTitle(_("Scroll in flow mode"))
        self.label_29.setText(_("Mouse wheel"))
        self.wheel_scroll_fraction.setToolTip(_("This is a percentage, by making it less than 100 you can decrease the amount the wheel scrolls by, by making it more than 100 you can increase the scroll amount."))
        self.wheel_scroll_fraction.setSuffix(_(" %"))
        self.label_30.setText(_("Arrow &keys"))
        self.line_scroll_fraction.setToolTip(_("This is a percentage, by making it less than 100 you can decrease the amount the arrow keys scroll by, by making it more than 100 you can increase the scroll amount."))
        self.line_scroll_fraction.setSuffix(_(" %"))
        self.line_scrolling_stops_on_pagebreaks.setText(_("Stop at page breaks"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _("Navigation"))
        self.add_dictionary_website_button.setText(_("&Add"))
        self.remove_dictionary_website_button.setText(_("&Remove"))
        self.change_dictionary_website_button.setText(_("&Edit"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _("Dictionary"))
        self.label_8.setText(_("Extension"))
        self.groupBox_12.setTitle(_("Remember"))
        self.synopsis_position.setText(_("Position"))
        self.synopsis_size.setText(_("Size and layout"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _("Synopsis"))
        self.groupBox_8.setTitle(_("Remember"))
        self.remember_window_size.setText(_("Size and layout"))
        self.remember_current_page.setText(_("Position"))
        self.groupBox_9.setTitle(_("Viewer"))
        self.fit_images.setToolTip(_("Needs restart"))
        self.fit_images.setText(_("&Resize larger images*"))
        self.singleinstance.setToolTip(_("Normally, you can view multiple books in calibre, each in its own viewer window. <br>With this option, if you attempt to view a second book, it will replace the previously opened book instead of using a new window. Needs restart"))
        self.singleinstance.setText(_("Single instance*"))
        self.show_controls.setText(_("Show &controls"))
        self.label_26.setText(_("&Search web url"))
        self.copy_bookmarks_to_file.setToolTip(_("Keep a copy of all bookmarks/current page information inside the ebook file, so that you can share them by simply sending the ebook file itself. Currently only works with ebooks in the EPUB format."))
        self.copy_bookmarks_to_file.setText(_("Copy &bookmarks and position into the book"))
        self.search_online_url.setToolTip(_("Change the search engine used to perform online searches for selected text.\n"
"You must enter the search URL for the search engine, with the placeholder\n"
"{text}, which will be replaced by the selected text."))
        self.clear_search_history_button.setText(_("Clear search history"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _("&Miscellaneous"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _("&General"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _("&Shortcuts"))
        self.user_css.setToolTip(_("Set the user CSS stylesheet. This can be used to customize the look of all books."))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _("S&tylesheet"))


